config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: 'tours#index'

  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end

  resources :tours do
    resources :bookings, only: [:new, :create]
  end
  
  resources :bookings, only: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :articles, only: [:index, :show]

  # patch 'carts/:id/discount', to: 'carts#discount', as: :discount

  get '/dashboard', to: 'pages#dashboard'
  get '/about_us', to: 'pages#about_us'
  get '/expert_team', to: 'pages#expert_team'
  get '/contact_us', to: 'pages#contact_us'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/faq', to: 'pages#faq'
  get '/cancellation_and_refund', to: 'pages#cancellation_and_refund'
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :photos

  acts_as_taggable_on :tags
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:tag].present?
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  def show
    @articles = Article.all
    @article = Article.find(params[:id])
    @related_articles = @article.find_related_tags
  end

  private

  def article_params
    params.require(:article).permit(:tag_list, :title, :content, :author, photos: [])
  end
end

app/views/articles/index.html.erb
<section class="blog-banner">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1605213605677-861baf60c228?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80);">
    <div class="container">
      <h1>Lorem <strong>ipsum</strong> dolor <strong>sit amet consectetur</strong>!</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsa tempore sint ipsum itaque, doloribus cupiditate? Laboriosam error quis nam maxime.</p>
    </div>
  </div>
</section>

<main class="container">
  <h1 id="anchor-tag" class="text-center mt-5 mb-5">Read <span class="span-logo span-logo-container">BERGIN</span> 's Unique Blog Posts</h1>
  <div class="row">
    <% @articles.each do |article| %>
      <div class="col-12 col-sm-8 col-md-6 col-lg-4 mb-5">
       <%= link_to article_path(article) do  %>
        <div class="card">
          <%= cl_image_tag article.photos[0].key, class: "card-img", alt: "#{article.title} Picture"  %>
          <div class="card-img-overlay">
            <button class="tag-btn"><%= article.author_img %></button>
          </div>
          <div class="card-body">
            <h4 class="card-title"><%= article.title %></h4>
            <p class="card-text mb-3">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
            <%= link_to "Continue reading", article_path(article), class: "blog-btn" %>
          </div>
          <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
            <div class="views"><%= article.created_at.strftime('%a, %d %b %Y') %></div>
            <div>
              <i class="fas fa-feather-alt"></i> <%= article.author %>
            </div>
          </div>
        </div>
       <% end %>
      </div>
    <% end %>
  </div>
</main>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div>
      <div class="text-center">
        <h1 class="mt-4 mb-3"><%= @article.title %></h1>
      </div>
      <%= @article.content.html_safe %>
    </div>
  </div>

  <div class="text-center">
    <%= link_to "Back to Blog Page", articles_path, class: "btn-blog-page mr-3" %>
    <%= link_to "Back to Home Page", tours_path, class: "btn-blog-home-page" %>
  </div>
</div>