config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: 'tours#index'

  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end

  resources :tours do
    resources :bookings, only: [:new, :create]
  end
  
  resources :bookings, only: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :articles, only: [:index, :show]

  # patch 'carts/:id/discount', to: 'carts#discount', as: :discount

  get '/dashboard', to: 'pages#dashboard'
  get '/about_us', to: 'pages#about_us'
  get '/expert_team', to: 'pages#expert_team'
  get '/contact_us', to: 'pages#contact_us'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/faq', to: 'pages#faq'
  get '/cancellation_and_refund', to: 'pages#cancellation_and_refund'
end

app/views/shared/_blue_navbar.html.erb
<header>
  <nav class="navbar nav-bar-blue nav-scroll navbar-expand-lg navbar-light">
        <div class="logo-container">
        <%= link_to "Bergin Tours", root_path, class: "navbar-brand text-white" %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Blog", articles_path, class: "nav-link text-white font-weight-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_us_path, class: "nav-link text-white font-weight-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "Services", tours_path(anchor: "anchor-tag"), class: "nav-link text-white font-weight-bold" %>
        </li>
      </ul>
      <div class="profile-container">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <% if current_user.nil? %>
            <li>
              <%= link_to "Log In", new_user_session_path, class: "pr-4 text-white" %>
              <button class="btn-signup mr-4"><%= link_to "Sign Up", new_user_registration_path %></button>
            </li>
          <% else %>
            <li>
              <button class="btn-signup mr-4 pr-4 pl-4"><%= link_to(cart_path(@user_cart)) do %>
                <i class="fas fa-shopping-cart"> <span class="size-shopping">( <%= @user_cart.bookings.size %> )</span></i><% end %></button>
              <%= link_to "Profile", dashboard_path, class: "mr-4 text-white" %>
              <%= link_to "Log Out", destroy_user_session_path,method: :delete, class: "mr-4 text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-section mt-5">
  <div class="container">
    <div class="footer-cta pt-5 pb-5">
      <div class="row">
        <div class="col-xl-4 col-md-4 mb-30">
          <div class="single-cta">
            <i class="fas fa-map-marker-alt"></i>
            <div class="cta-text mb-4">
              <h4>Find us</h4>
              <span>Yavansu, Manolya Sk. Kuşadası/Aydın, Turkey</span>
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-md-4 mb-30">
          <div class="single-cta">
            <i class="fas fa-phone"></i>
            <div class="cta-text mb-4">
              <h4>Call us</h4>
              <span>+90 535 826 43 92</span>
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-md-4 mb-30">
          <div class="single-cta">
            <i class="far fa-envelope-open"></i>
            <div class="cta-text">
              <h4>Mail us</h4>
              <span>info@bergintours.com</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-content pt-5 pb-5">
      <div class="row">
        <div class="col-xl-4 col-lg-4 mb-50">
          <div class="footer-widget">
            <div class="footer-logo logo-container">
              <h3 class="text-white">Bergin Tours</h3>
              <%# <a href="index.html"><img src="https://i.ibb.co/QDy827D/ak-logo.png" class="img-fluid" alt="logo"></a> %>
            </div>
            <div class="footer-text">
              <p>Bergin Tours Company is owned and operated by Bergin Tours Travel Agency. 
              Bergin Tours Travel Agency located in Istanbul, Kusadasi and Cappadocia.
              Founded in 1989, an A Group licenced Travel Agency (A-2479) and 
              member of TURSAB (Association of Turkish Travel Agencies) since 1994.</p>
            </div>
            <div class="footer-social-icon">
              <span>Follow us</span>
                <%= link_to("https://www.instagram.com/gototravelturkey/", target: "_blank") do %>
                  <i class="fab fa-instagram"></i>
                <% end %>

                <%= link_to("https://www.tripadvisor.com/Attraction_Review-g297972-d19259003-Reviews-Turkey_Tours_Company-Kusadasi_Turkish_Aegean_Coast.html", target: "_blank") do %>
                  <i class="fab fa-tripadvisor"></i>
                <% end %>

                <%= link_to("https://www.facebook.com/turkeytourscompany", target: "_blank") do %>
                  <i class="fab fa-facebook-f"></i>
                <% end %>

                <%= link_to("https://www.linkedin.com/in/anil-pak/", target: "_blank") do %>
                  <i class="fab fa-linkedin-in"></i>
                <% end %>
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-6 mb-30">
          <div class="footer-widget">
            <div class="footer-widget-heading mt-4">
              <h3>Useful Links</h3>
            </div>
            <ul>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About Us", about_us_path %></li>
              <li><%= link_to "Expert Team", expert_team_path %></li>
              <li><%= link_to "Contact Us", contact_us_path %></li>
            </ul>
          </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-6 mb-50">
          <div class="footer-widget">
            <div class="footer-widget-heading">
              <h3>Subscribe</h3>
            </div>
            <div class="footer-text mb-25">
              <p>Don’t miss to subscribe to our new feeds, kindly fill the form below.</p>
            </div>
            <div class="subscribe-form">
              <form action="#">
                <input type="text" placeholder="Email Address">
                <button><i class="fab fa-telegram-plane"></i></button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright-area">
    <div class="container">
      <div class="row">
        <div class="col-xl-6 col-lg-6 text-center text-lg-left">
          <div class="copyright-text">
            <p>Copyright &copy; 2021, All Right Reserved <%= link_to "Anıl Pak", "https://anilpak.com/", target: "_blank" %></p>
          </div>
        </div>
        <div class="col-xl-6 col-lg-6 d-none d-lg-block text-right">
          <div class="footer-menu">
            <ul>
              <li><%= link_to "Terms and Conditions", terms_and_conditions_path %></li>
              <li><%= link_to "FAQ", faq_path %></li>
              <li><%= link_to "Cancellation and Refund", cancellation_and_refund_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar fixed-top nav-scroll navbar-expand-lg navbar-light">
    <div class="logo-container">
        <%= link_to "Bergin Tours", root_path, class: "navbar-brand text-white" %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Blog", articles_path, class: "nav-link text-white font-weight-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", about_us_path, class: "nav-link text-white font-weight-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "Services", tours_path(anchor: "anchor-tag"), class: "nav-link text-white font-weight-bold" %>
        </li>
      </ul>
      <div class="profile-container">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <% if current_user.nil? %>
            <li>
              <%= link_to "Log In", new_user_session_path, class: "pr-4 text-white" %>
              <button class="btn-signup mr-4"><%= link_to "Sign Up", new_user_registration_path %></button>
            </li>
          <% else %>
            <li>
              <button class="btn-signup mr-4 pr-4 pl-4"><%= link_to(cart_path(@user_cart)) do %>
              <i class="fas fa-shopping-cart"> <span class="size-shopping">( <%= @user_cart.bookings.size %> )</span></i><% end %></button>
              <%= link_to "Profile", dashboard_path, class: "mr-4 text-white" %>
              <%= link_to "Log Out", destroy_user_session_path,method: :delete, class: "mr-4 text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>