config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: 'tours#index'

  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end

  resources :tours do
    resources :bookings, only: [:new, :create]
  end
  
  resources :bookings, only: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :carts, only: [:show, :update]

  resources :articles, only: [:index, :show]

  # patch 'carts/:id/discount', to: 'carts#discount', as: :discount

  get '/dashboard', to: 'pages#dashboard'
  get '/about_us', to: 'pages#about_us'
  get '/expert_team', to: 'pages#expert_team'
  get '/contact_us', to: 'pages#contact_us'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/faq', to: 'pages#faq'
  get '/cancellation_and_refund', to: 'pages#cancellation_and_refund'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :bookings

  enum state: ["open", "confirmed", "paid"]

  def calculate_total_price
    prices = self.bookings.map do |booking|
      booking.calculate_total_price
    end
    prices.sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show 
    @user = current_user
    @cart = Cart.find(params[:id])

    if (@cart.calculate_total_price.to_i == 0)
      @cart.update(checkout_session_id: nil)
    else
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: "Thanks for booking #{ @cart.bookings[0].tour.title}",
        images: @cart.bookings.map do |booking|
          Cloudinary::Utils.cloudinary_url(booking.tour.photos[0].key)
        end,
        amount: @cart.calculate_total_price.to_i * 100,
        currency: 'usd',
        quantity: 1
      }],
      success_url: cart_url(@cart, pay: "true"),
      cancel_url: cart_url(@cart)
    )
    @cart.update(checkout_session_id: session.id)
    end
  end

  # def discount 
  #   @cart = Cart.find(params[:id])
  #   @cart.bookings { |booking| booking.update(calculate_total_price: booking.calculate_total_price * 0.75) }
  #   flash[:notice] = "You're discount code has been accepted"
  #   session[:discount] = true
  #   redirect_to @cart
  # end
end

app/views/carts/show.html.erb
<main class="cart-main-container">
  <section>
    <div class="container">
      <div class="row">
        <div class="card mt-5 col-lg-8 mb-3" style="min-width: 14rem;">
          <div class="my-4">
            <h1>Your Travel Destinations</h1>
            <p>Thanks for your booking <strong><%= current_user.email %></strong></p>
          </div>
          <div class="promotion-code my-1">
            <div><label class="h4" for="promo-code">Enter a promotional code</label></div>
            <input id="promo-code" type="text" name="promo-code" maxlength="8" class="promo-code-field">
            <button class="btn btn-success ml-4">Apply</button>
            <%#= link_to "Apply", discount_path(@cart), class: "ml-3 btn btn-success", method: :patch %>
          </div>
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Tour</th>
                  <th scope="col">Tour Name</th>
                  <th scope="col">Pax</th>
                  <th scope="col">Start date</th>
                  <th scope="col">Total Price</th>  
                </tr>
              </thead>
              <tbody>
                <% @cart.bookings.each do |booking| %>
                  <tr>
                    <th scope="row"><%= cl_image_tag booking.tour.photos[0].key, class: "cart-page-img", alt: "#{booking.tour.title} Picture"  %></th>
                    <td><%= booking.tour.title %></td>
                    <td><% if booking.number_of_children.to_i > 0 && booking.number_of_infant.to_i > 0 %>
                          <%= booking.number_of_adult %> adult +<%= booking.number_of_children %> children + <%= booking.number_of_infant %> infant
                        <% elsif booking.number_of_children.to_i == 0 && booking.number_of_infant.to_i == 0 %>
                          <%= booking.number_of_adult %> adult
                        <% elsif booking.number_of_children.to_i > 0 && booking.number_of_infant.to_i == 0  %>
                          <%= booking.number_of_adult %> adult + <%= booking.number_of_children %> children
                        <% elsif booking.number_of_adult.to_i > 0 && booking.number_of_children.to_i == 0 %>
                          <%= booking.number_of_adult %> adult + <%= booking.number_of_infant %> infant
                        <% end %>
                        </td>
                    <td><%= booking.start_date.strftime('%a, %d %b %Y') %></td>
                    <td><%= humanized_money_with_symbol(booking.calculate_total_price) %></td>
                    <%#= session[:discount] ? booking.calculate_total_price * 0.75 : booking.calculate_total_price %> 
                        <%#= session[:discount] = nil  %>
                    <td><%= link_to "Remove", booking_path(booking), method: :delete, class: "btn btn-sm btn-danger" %></td>
                  </tr>
                <%end%>
              </tbody>
            </table>
          </div>

        </div>
        <div class="card col-lg-3 mt-5 mb-3 ml-2 h-75 d-inline-block">
          <h5 class="text-center my-3"><u>Your Shopping Bag</u></h5>
          <div class="summary-subtotal">
            <p>Subtotal: <%= humanized_money_with_symbol(@cart.calculate_total_price) %></p>
            <p class="promo-title">Promotion:</p>
          </div>
          <div class="summary-total">
            <p>Total: <%= humanized_money_with_symbol(@cart.calculate_total_price) %></p>
          </div>
          <div class="summary-checkout">
          <% if params[:pay] %>
            <h2>Paid</h2>
              <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
                We have received your payment
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% elsif (@cart.checkout_session_id) %>
            <button id="pay" class="btn btn-lg btn-warning my-3">Go to Secure Checkout</button>
            <script src="https://js.stripe.com/v3/"></script>
            <script>
              var paymentButton = document.getElementById('pay');
              paymentButton.addEventListener('click', () => {
              const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
              stripe.redirectToCheckout({
              sessionId: '<%= @cart.checkout_session_id %>'
                });
              });
            </script>
          <% else %>
            <button disabled id="pay" class="btn btn-lg btn-warning my-3">Go to Secure Checkout</button>
          <% end %> 
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
<div>
  <div class="text-center mb-3">
    <%= link_to "Book Another Tour", tours_path, class: "btn btn-primary" %>
  </div>
</div>